# NixOS module. Optional — the primary install path is the home-manager module (the tray
# is a per-user thing). This module is a thin wrapper that can install the package
# system-wide and, optionally, grant a trusted user passwordless "apply" via polkit.
{ config, lib, pkgs, ... }:
let
  cfg = config.services.nixos-update-notifier;
  pkg = cfg.package;
in
{
  options.services.nixos-update-notifier = {
    enable = lib.mkEnableOption "system-wide install of nixos-update-notifier";

    package = lib.mkOption {
      type = lib.types.package;
      # Built from YOUR nixpkgs, not this flake's. Defaulting to
      # `self.packages.<system>.default` would drag our nixpkgs pin into your closure as a
      # second nixpkgs tree — duplicating glibc, GTK4 and everything under them — purely
      # because we happen to track a different channel. callPackage keeps the build on your
      # channel; the overlay is there if you would rather have `pkgs.nixos-update-notifier`.
      default = pkgs.callPackage ./package.nix { };
      defaultText = lib.literalExpression "pkgs.callPackage ./package.nix { }";
      description = "The nixos-update-notifier package to install.";
    };

    installSystemPackage = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Add the package to environment.systemPackages.";
    };

    polkit.passwordlessUsers = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      example = [ "you" ];
      description = ''
        Users allowed to run the notifier's privileged apply via pkexec WITHOUT
        re-authenticating. Leave empty to require the normal polkit admin prompt each time
        (the safe default).

        SECURITY: enabling this is equivalent to granting NOPASSWD sudo to these users.
        The privileged step runs `nixos-rebuild switch` against the flake in the configured
        checkout, and that checkout is writable by its owner — so anyone able to execute
        code as such a user can edit flake.nix and have root run it at the next apply,
        with no prompt. The interactive polkit prompt is what normally prevents this by
        requiring a present, consenting human. Only enable this if you would also be
        comfortable giving these users passwordless root.
      '';
    };
  };

  config = lib.mkIf cfg.enable (lib.mkMerge [
    (lib.mkIf cfg.installSystemPackage {
      environment.systemPackages = [ pkg ];
    })

    (lib.mkIf (cfg.polkit.passwordlessUsers != [ ]) {
      security.polkit.enable = true;
      security.polkit.extraConfig =
        let
          users = lib.concatStringsSep ", " (map (u: "\"${u}\"") cfg.polkit.passwordlessUsers);
        in
        ''
          // Generated by services.nixos-update-notifier: passwordless apply for trusted users.
          // Scoped to the notifier DAEMON only — matched by exact path, never by prefix.
          // The package's bin/ also contains the GTK client (and both makeBinaryWrapper
          // `.…-wrapped` binaries); a prefix match would hand those passwordless root too,
          // which is far wider than "apply updates" needs. The daemon pkexecs
          // `current_exe()`, which under the wrapper resolves to the `-wrapped` path, so
          // both spellings of the daemon are listed and nothing else is.
          polkit.addRule(function (action, subject) {
            var program = action.lookup("program") || "";
            var allowed = [
              "${pkg}/bin/nixos-update-notifier",
              "${pkg}/bin/.nixos-update-notifier-wrapped"
            ];
            if (
              action.id === "org.freedesktop.policykit.exec" &&
              allowed.indexOf(program) !== -1 &&
              [${users}].indexOf(subject.user) !== -1
            ) {
              return polkit.Result.YES;
            }
          });
        '';
    })
  ]);
}
