# NixOS module. Optional — the primary install path is the home-manager module (the tray
# is a per-user thing). This module is a thin wrapper that can install the package
# system-wide and, optionally, grant a trusted user passwordless "apply" via polkit.
self:
{ config, lib, pkgs, ... }:
let
  cfg = config.services.nixos-update-notifier;
  pkg = cfg.package;
in
{
  options.services.nixos-update-notifier = {
    enable = lib.mkEnableOption "system-wide install of nixos-update-notifier";

    package = lib.mkOption {
      type = lib.types.package;
      default = self.packages.${pkgs.stdenv.hostPlatform.system}.default;
      defaultText = lib.literalExpression "nixos-update-notifier.packages.\${system}.default";
      description = "The nixos-update-notifier package to install.";
    };

    installSystemPackage = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Add the package to environment.systemPackages.";
    };

    polkit.passwordlessUsers = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      example = [ "you" ];
      description = ''
        Users allowed to run the notifier's privileged apply via pkexec WITHOUT
        re-authenticating. Leave empty to require the normal polkit admin prompt each time
        (the safe default).
      '';
    };
  };

  config = lib.mkIf cfg.enable (lib.mkMerge [
    (lib.mkIf cfg.installSystemPackage {
      environment.systemPackages = [ pkg ];
    })

    (lib.mkIf (cfg.polkit.passwordlessUsers != [ ]) {
      security.polkit.enable = true;
      security.polkit.extraConfig =
        let
          users = lib.concatStringsSep ", " (map (u: "\"${u}\"") cfg.polkit.passwordlessUsers);
        in
        ''
          // Generated by services.nixos-update-notifier: passwordless apply for trusted users.
          // Match any executable in the package's bin/ (the daemon re-execs its own
          // makeBinaryWrapper-wrapped path, so we prefix-match rather than exact-match).
          polkit.addRule(function (action, subject) {
            var program = action.lookup("program") || "";
            if (
              action.id === "org.freedesktop.policykit.exec" &&
              program.indexOf("${pkg}/bin/") === 0 &&
              [${users}].indexOf(subject.user) !== -1
            ) {
              return polkit.Result.YES;
            }
          });
        '';
    })
  ]);
}
